apiVersion: networking.istio.io/v1alpha3
kind: VirtualService
metadata:
  name: ts-basic-service
spec:
  hosts:
  - ts-basic-service
  http:
  - match:
    - headers:
        end-user:
          exact: fdse_microservice
    fault:
      delay:
        fixedDelay: 7s
        percentage:
          value: 100.0
        
    route:
    - destination:
        host: ts-basic-service 
        subset: v1
  - route:
    - destination:
        host: ts-basic-service
        subset: v2
